# Project creation
# create_project csi2_example . -part xc7z020clg400-1
# Creating new block design
# create_bd_design "design_1"
# Adding ZYNQ-7000 Processing System
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 processing_system7_0
# Configuring PS
# Clock ratio
set_property CONFIG.PCW_APU_CLK_RATIO_ENABLE "6:2:1" [get_bd_cells processing_system7_0]
# Input clock frequency
set_property CONFIG.PCW_CRYSTAL_PERIPHERAL_FREQMHZ "33.333333" [get_bd_cells processing_system7_0]
# Allows us to configure dividers of PLL
set_property CONFIG.PCW_OVERRIDE_BASIC_CLOCK "1" [get_bd_cells processing_system7_0]
# 33 * 39 = 1300 MHz ARM PLL frequency
set_property CONFIG.PCW_ARMPLL_CTRL_FBDIV "39" [get_bd_cells processing_system7_0]
# 33 * 32 = 1066 MHz DDR PLL frequency
set_property CONFIG.PCW_DDRPLL_CTRL_FBDIV "32" [get_bd_cells processing_system7_0]
# 33 * 30 = 1000 MHz IO PLL frequency
set_property CONFIG.PCW_IOPLL_CTRL_FBDIV "30" [get_bd_cells processing_system7_0]
# Clock ARM core from ARM PLL
set_property CONFIG.PCW_CPU_PERIPHERAL_CLKSRC "ARM PLL" [get_bd_cells processing_system7_0]
# 1300 / 2 = 650 MHz actual ARM core clock frequency
set_property CONFIG.PCW_CPU_PERIPHERAL_DIVISOR0 "2" [get_bd_cells processing_system7_0]
# Banks voltages
set_property CONFIG.PCW_PRESET_BANK0_VOLTAGE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_PRESET_BANK1_VOLTAGE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
# DDR3 memory settings
# Address space for DDR memory
set_property CONFIG.PCW_DDR_RAM_HIGHADDR "0x3FFFFFFF" [get_bd_cells processing_system7_0]
# Dynamicaly controlled impendance
# Clock DCI from DDR PLL
set_property CONFIG.PCW_DCI_PERIPHERAL_CLKSRC "DDR PLL" [get_bd_cells processing_system7_0]
# DCI clock divisors
set_property CONFIG.PCW_DCI_PERIPHERAL_DIVISOR0 "15" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DCI_PERIPHERAL_DIVISOR1 "7" [get_bd_cells processing_system7_0]
# Advanced DDR settings
set_property CONFIG.PCW_UIPARAM_DDR_ADV_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DDR_HPR_TO_CRITICAL_PRIORITY_LEVEL "15" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DDR_LPR_TO_CRITICAL_PRIORITY_LEVEL "2" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DDR_PERIPHERAL_CLKSRC "DDR PLL" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DDR_PERIPHERAL_DIVISOR0 "2" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DDR_WRITE_TO_CRITICAL_PRIORITY_LEVEL "2" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_AL "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_BANK_ADDR_COUNT "3" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_BL "8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY0 "0.221" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY1 "0.222" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY2 "0.217" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY3 "0.244" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_BUS_WIDTH "32 Bit" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CL "7" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_0_LENGTH_MM "18.8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_0_PACKAGE_LENGTH "80.4535" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_0_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_1_LENGTH_MM "18.8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_1_PACKAGE_LENGTH "80.4535" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_1_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_2_LENGTH_MM "18.8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_2_PACKAGE_LENGTH "80.4535" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_2_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_3_LENGTH_MM "18.8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_3_PACKAGE_LENGTH "80.4535" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_3_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_STOP_EN "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_COL_ADDR_COUNT "10" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CWL "6" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DEVICE_CAPACITY "4096 MBits" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_0_LENGTH_MM "22.8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_0_PACKAGE_LENGTH "105.056" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_0_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_1_LENGTH_MM "27.9" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_1_PACKAGE_LENGTH "66.904" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_1_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_2_LENGTH_MM "22.9" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_2_PACKAGE_LENGTH "89.1715" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_2_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_3_LENGTH_MM "29.4" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_3_PACKAGE_LENGTH "113.63" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_3_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0 "0.001" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1 "0.001" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_2 "0.001" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_3 "0.001" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_0_LENGTH_MM "22.8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_0_PACKAGE_LENGTH "98.503" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_0_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_1_LENGTH_MM "27.9" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_1_PACKAGE_LENGTH "68.5855" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_1_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_2_LENGTH_MM "22.9" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_2_PACKAGE_LENGTH "90.295" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_2_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_3_LENGTH_MM "29.4" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_3_PACKAGE_LENGTH "103.977" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_3_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DRAM_WIDTH "16 Bits" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_ECC "Disabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_FREQ_MHZ "533.333333" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_HIGH_TEMP "Normal (0-85)" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_MEMORY_TYPE "DDR 3 (Low Voltage)" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_PARTNO "MT41K256M16 RE-125" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_ROW_ADDR_COUNT "15" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_SPEED_BIN "DDR3_1066F" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_TRAIN_DATA_EYE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_TRAIN_READ_GATE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_TRAIN_WRITE_LEVEL "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_T_FAW "40.0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_T_RAS_MIN "35.0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_T_RC "48.75" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_T_RCD "7" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_T_RP "7" [get_bd_cells processing_system7_0]
# QSPI
set_property CONFIG.PCW_QSPI_GRP_FBCLK_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_GRP_FBCLK_IO "MIO 8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_GRP_IO1_ENABLE "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_GRP_SINGLE_SS_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_GRP_SINGLE_SS_IO "MIO 1 .. 6" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_GRP_SS1_ENABLE "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_INTERNAL_HIGHADDRESS "0xFCFFFFFF" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_PERIPHERAL_CLKSRC "IO PLL" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_PERIPHERAL_DIVISOR0 "5" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_PERIPHERAL_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_PERIPHERAL_FREQMHZ "200" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_QSPI_IO "MIO 1 .. 6" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_19_SLEW "fast" [get_bd_cells processing_system7_0]
# MIO for QSPI
set_property CONFIG.PCW_MIO_1_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_1_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_1_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_1_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_2_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_2_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_2_PULLUP "disabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_2_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_3_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_3_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_3_PULLUP "disabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_3_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_4_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_4_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_4_PULLUP "disabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_4_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_5_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_5_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_5_PULLUP "disabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_5_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_6_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_6_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_6_PULLUP "disabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_6_SLEW "slow" [get_bd_cells processing_system7_0]
# UART
set_property CONFIG.PCW_UART_PERIPHERAL_CLKSRC "IO PLL" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UART_PERIPHERAL_DIVISOR0 "10" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UART1_BAUD_RATE "115200" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UART1_GRP_FULL_ENABLE "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UART1_PERIPHERAL_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UART1_UART1_IO "MIO 48 .. 49" [get_bd_cells processing_system7_0]
# MIO for UART
set_property CONFIG.PCW_MIO_48_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_48_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_48_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_48_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_49_DIRECTION "in" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_49_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_49_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_49_SLEW "slow" [get_bd_cells processing_system7_0]
# Disabling M_AXI_GP0
set_property CONFIG.PCW_USE_M_AXI_GP0 "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_USE_CROSS_TRIGGER "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_USE_AXI_NONSECURE "0" [get_bd_cells processing_system7_0]
# Make DDR and FIXED_IO external
make_bd_intf_pins_external  [get_bd_intf_pins processing_system7_0/FIXED_IO]
make_bd_intf_pins_external  [get_bd_intf_pins processing_system7_0/DDR]
