# Project creation
create_project csi2_example . -part xc7z020clg400-1
# Creating new block design
create_bd_design "design_1"
# Adding ZYNQ-7000 Processing System
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 processing_system7_0
# Configuring PS
set_property CONFIG.PCW_DDR_RAM_HIGHADDR "0x3FFFFFFF" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_APU_CLK_RATIO_ENABLE "6:2:1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_APU_PERIPHERAL_FREQMHZ "667" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ARMPLL_CTRL_FBDIV "39" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_CPU_CPU_PLL_FREQMHZ "1300.000" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_CPU_PERIPHERAL_CLKSRC "ARM PLL" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_CPU_PERIPHERAL_DIVISOR0 "2" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_CRYSTAL_PERIPHERAL_FREQMHZ "33.333333" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DCI_PERIPHERAL_CLKSRC "DDR PLL" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DCI_PERIPHERAL_DIVISOR0 "15" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DCI_PERIPHERAL_DIVISOR1 "7" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DCI_PERIPHERAL_FREQMHZ "10.159" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DDRPLL_CTRL_FBDIV "32" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DDR_DDR_PLL_FREQMHZ "1066.667" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DDR_HPRLPR_QUEUE_PARTITION "HPR(0)/LPR(32)" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DDR_HPR_TO_CRITICAL_PRIORITY_LEVEL "15" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DDR_LPR_TO_CRITICAL_PRIORITY_LEVEL "2" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DDR_PERIPHERAL_CLKSRC "DDR PLL" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DDR_PERIPHERAL_DIVISOR0 "2" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_DDR_WRITE_TO_CRITICAL_PRIORITY_LEVEL "2" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET0_ENET0_IO "MIO 16 .. 27" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET0_GRP_MDIO_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET0_GRP_MDIO_IO "MIO 52 .. 53"	 [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET0_PERIPHERAL_CLKSRC "IO PLL" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET0_PERIPHERAL_DIVISOR0 "8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET0_PERIPHERAL_DIVISOR1 "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET0_PERIPHERAL_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET0_PERIPHERAL_FREQMHZ "1000 Mbps" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET1_PERIPHERAL_CLKSRC "IO PLL" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET1_PERIPHERAL_DIVISOR0 "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET1_PERIPHERAL_DIVISOR1 "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET1_PERIPHERAL_ENABLE "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET1_PERIPHERAL_FREQMHZ "1000 Mbps" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET_RESET_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET_RESET_POLARITY "Active Low" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_ENET_RESET_SELECT "Share reset pin" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_EN_4K_TIMER "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_GPIO_MIO_GPIO_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_GPIO_MIO_GPIO_IO "MIO" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_GPIO_PERIPHERAL_ENABLE "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_IOPLL_CTRL_FBDIV "30" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_IO_IO_PLL_FREQMHZ "1000.000" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_IRQ_F2P_MODE "DIRECT" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_0_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_0_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_0_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_0_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_10_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_10_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_10_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_10_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_11_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_11_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_11_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_11_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_12_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_12_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_12_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_12_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_13_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_13_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_13_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_13_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_14_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_14_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_14_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_14_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_15_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_15_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_15_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_15_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_16_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_16_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_16_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_16_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_17_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_17_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_17_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_17_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_18_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_18_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_18_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_18_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_19_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_19_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_19_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_19_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_1_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_1_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_1_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_1_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_20_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_20_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_20_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_20_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_21_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_21_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_21_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_21_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_22_DIRECTION "in" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_22_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_22_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_22_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_23_DIRECTION "in" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_23_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_23_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_23_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_24_DIRECTION "in" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_24_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_24_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_24_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_25_DIRECTION "in" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_25_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_25_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_25_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_26_DIRECTION "in" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_26_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_26_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_26_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_27_DIRECTION "in" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_27_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_27_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_27_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_28_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_28_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_28_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_28_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_29_DIRECTION "in" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_29_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_29_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_29_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_2_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_2_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_2_PULLUP "disabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_2_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_30_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_30_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_30_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_30_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_31_DIRECTION "in" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_31_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_31_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_31_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_32_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_32_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_32_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_32_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_33_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_33_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_33_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_33_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_34_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_34_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_34_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_34_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_35_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_35_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_35_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_35_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_36_DIRECTION "in" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_36_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_36_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_36_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_37_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_37_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_37_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_37_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_38_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_38_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_38_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_38_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_39_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_39_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_39_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_39_SLEW "fast" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_3_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_3_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_3_PULLUP "disabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_3_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_40_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_40_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_40_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_40_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_41_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_41_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_41_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_41_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_42_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_42_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_42_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_42_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_43_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_43_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_43_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_43_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_44_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_44_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_44_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_44_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_45_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_45_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_45_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_45_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_46_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_46_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_46_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_46_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_47_DIRECTION "in" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_47_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_47_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_47_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_48_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_48_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_48_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_48_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_49_DIRECTION "in" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_49_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_49_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_49_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_4_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_4_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_4_PULLUP "disabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_4_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_50_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_50_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_50_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_50_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_51_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_51_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_51_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_51_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_52_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_52_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_52_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_52_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_53_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_53_IOTYPE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_53_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_53_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_5_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_5_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_5_PULLUP "disabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_5_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_6_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_6_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_6_PULLUP "disabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_6_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_7_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_7_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_7_PULLUP "disabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_7_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_8_DIRECTION "out" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_8_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_8_PULLUP "disabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_8_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_9_DIRECTION "inout" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_9_IOTYPE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_9_PULLUP "enabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_MIO_9_SLEW "slow" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_OVERRIDE_BASIC_CLOCK "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_PCAP_PERIPHERAL_CLKSRC "IO PLL" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_PCAP_PERIPHERAL_DIVISOR0 "5" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_PCAP_PERIPHERAL_FREQMHZ "200" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_PJTAG_PERIPHERAL_ENABLE "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_PLL_BYPASSMODE_ENABLE "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_PRESET_BANK0_VOLTAGE "LVCMOS 3.3V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_PRESET_BANK1_VOLTAGE "LVCMOS 1.8V" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_GRP_FBCLK_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_GRP_FBCLK_IO "MIO 8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_GRP_IO1_ENABLE "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_GRP_SINGLE_SS_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_GRP_SINGLE_SS_IO "MIO 1 .. 6" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_GRP_SS1_ENABLE "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_INTERNAL_HIGHADDRESS "0xFCFFFFFF" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_PERIPHERAL_CLKSRC "IO PLL" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_PERIPHERAL_DIVISOR0 "5" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_PERIPHERAL_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_PERIPHERAL_FREQMHZ "200" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_QSPI_QSPI_IO "MIO 1 .. 6" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_SD0_GRP_CD_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_SD0_GRP_CD_IO "MIO 47" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_SD0_GRP_POW_ENABLE "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_SD0_GRP_WP_ENABLE "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_SD0_PERIPHERAL_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_SD0_SD0_IO "MIO 40 .. 45" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_SDIO_PERIPHERAL_CLKSRC "IO PLL" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_SDIO_PERIPHERAL_DIVISOR0 "20" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_SDIO_PERIPHERAL_FREQMHZ "50" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_SMC_PERIPHERAL_CLKSRC "IO PLL" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_SMC_PERIPHERAL_DIVISOR0 "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_SMC_PERIPHERAL_FREQMHZ "100" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_TPIU_PERIPHERAL_CLKSRC "External" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_TPIU_PERIPHERAL_DIVISOR0 "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_TPIU_PERIPHERAL_FREQMHZ "200" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UART1_BAUD_RATE "115200" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UART1_GRP_FULL_ENABLE "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UART1_PERIPHERAL_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UART1_UART1_IO "MIO 48 .. 49" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UART_PERIPHERAL_CLKSRC "IO PLL" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UART_PERIPHERAL_DIVISOR0 "10" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UART_PERIPHERAL_FREQMHZ "100" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_ADV_ENABLE "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_AL "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_BANK_ADDR_COUNT "3" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_BL "8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY0 "0.221" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY1 "0.222" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY2 "0.217" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY3 "0.244" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_BUS_WIDTH "32 Bit" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CL "7" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_0_LENGTH_MM "18.8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_0_PACKAGE_LENGTH "80.4535" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_0_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_1_LENGTH_MM "18.8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_1_PACKAGE_LENGTH "80.4535" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_1_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_2_LENGTH_MM "18.8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_2_PACKAGE_LENGTH "80.4535" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_2_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_3_LENGTH_MM "18.8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_3_PACKAGE_LENGTH "80.4535" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_3_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CLOCK_STOP_EN "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_COL_ADDR_COUNT "10" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_CWL "6" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DEVICE_CAPACITY "4096 MBits" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_0_LENGTH_MM "22.8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_0_PACKAGE_LENGTH "105.056" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_0_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_1_LENGTH_MM "27.9" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_1_PACKAGE_LENGTH "66.904" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_1_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_2_LENGTH_MM "22.9" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_2_PACKAGE_LENGTH "89.1715" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_2_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_3_LENGTH_MM "29.4" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_3_PACKAGE_LENGTH "113.63" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_3_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0 "-0.050" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1 "-0.044" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_2 "-0.035" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_3 "-0.100" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_0_LENGTH_MM "22.8" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_0_PACKAGE_LENGTH "98.503" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_0_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_1_LENGTH_MM "27.9" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_1_PACKAGE_LENGTH "68.5855" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_1_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_2_LENGTH_MM "22.9" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_2_PACKAGE_LENGTH "90.295" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_2_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_3_LENGTH_MM "29.4" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_3_PACKAGE_LENGTH "103.977" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DQ_3_PROPOGATION_DELAY "160" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_DRAM_WIDTH "16 Bits" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_ECC "Disabled" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_FREQ_MHZ "533.333333" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_HIGH_TEMP "Normal (0-85)" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_MEMORY_TYPE "DDR 3 (Low Voltage)" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_PARTNO "MT41K256M16 RE-125" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_ROW_ADDR_COUNT "15" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_SPEED_BIN "DDR3_1066F" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_TRAIN_DATA_EYE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_TRAIN_READ_GATE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_TRAIN_WRITE_LEVEL "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_T_FAW "40.0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_T_RAS_MIN "35.0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_T_RC "48.75" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_T_RCD "7" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_T_RP "7" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_UIPARAM_DDR_USE_INTERNAL_VREF "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_USB0_PERIPHERAL_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_USB0_PERIPHERAL_FREQMHZ "60" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_USB0_RESET_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_USB0_RESET_IO "MIO 46" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_USB0_USB0_IO "MIO 28 .. 39" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_USB_RESET_ENABLE "1" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_USB_RESET_POLARITY "Active Low" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_USB_RESET_SELECT "Share reset pin" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_USE_AXI_NONSECURE "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_USE_CROSS_TRIGGER "0" [get_bd_cells processing_system7_0]
set_property CONFIG.PCW_USE_M_AXI_GP0 "1" [get_bd_cells processing_system7_0]
